name: Prepare Release
on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    release:
        name: Prepare Release
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: write
            pull-requests: write

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
                  cache: 'npm'

            - name: Install Dependencies
              run: npm i

            - name: Build
              run: npm run build

            - name: Create Release Pull Request or Publish
              uses: changesets/action@v1
              with:
                  title: New Release
                  publish: npx changeset publish
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
